In [ ]:
import sys
import pandas as pd
import matplotlib
import numpy as np
import scipy as sp
import IPython 
import sklearn
from pandas.plotting import scatter_matrix

In [ ]:
from sklearn.datasets import load_iris

iris_dataset = load_iris()

In [ ]:
print(f'Keys from dataset: {iris_dataset.keys()}')

Keys from dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print(iris_dataset['DESCR'][:193] + '\n...')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [ ]:
print(f"target_names: {iris_dataset['target_names']}")

target_names: ['setosa' 'versicolor' 'virginica']


In [ ]:
print(f"Feature_names: {iris_dataset['feature_names']}")

Feature_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print(f"Shape of data: {iris_dataset['data'].shape}")

Shape of data: (150, 4)


In [ ]:
print(f"First five columns of data:\n {iris_dataset['data'][:5]}")

First five columns of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [ ]:
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)

grr = pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15, 15), marker='o', hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

NameError: ignored

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [8]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print(f"X_new.shape: {X_new.shape}")

X_new.shape: (1, 4)


In [9]:
prediction = knn.predict(X_new)
print(f"Prediction: {prediction}")
print(f"Predicted target name: {iris_dataset['target_names'][prediction]}")

Prediction: [0]
Predicted target name: ['setosa']


In [11]:
y_pred = knn.predict(X_test)
print(f"Test set prediction: {y_pred}")

Test set prediction: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [12]:
print(f"Test set score: {np.mean(y_pred == y_test):.2f}")

Test set score: 0.97


In [13]:
print(f"Test set score: {knn.score(X_test, y_test):.2f}")

Test set score: 0.97
